# Generated by Django 3.0.4 on 2020-03-04 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal_value', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Times', 'Times'), ('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Units', 'Units'), ('Steps', 'Steps')], max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='habit_log', to='core.Habit')),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
