# Generated by Django 3.0.4 on 2020-03-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('habit', 'activity_date')},
        ),
    ]
