# Generated by Django 3.0.4 on 2020-03-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200306_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
