# Generated by Django 3.0.4 on 2020-03-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200306_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-activity_date']},
        ),
    ]
