# Generated by Django 3.0.4 on 2020-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200308_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(default='unit', max_length=100),
        ),
    ]
