# Generated by Django 3.0.4 on 2020-03-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200309_0231'),
        ('core', '0005_auto_20200309_0220'),
    ]

    operations = [
    ]
